<script lang="ts">
 import {onMount,onDestroy} from 'svelte';import StartRoom from './components/StartRoom.svelte';import SenderRoom from './components/SenderRoom.svelte';import ReceiverRoom from './components/ReceiverRoom.svelte';
 import {base64url,fromBase64url,randomBytes,randomId,generatePin,derivePairingKey,deriveSessionKeys,encryptJson,decryptJson,ReplayGuard,normalizePin,type SessionKeys} from './crypto';import type {EncryptedEnvelope} from '../shared/envelope';import {MAX_PLAINTEXT_BYTES} from '../shared/envelope';
 type Item={id:string;label:string;value:string;createdAt:number;expiresAt:number;ttl:number};type Stored={role:'sender'|'receiver';roomId:string;roomKey:string;pin:string;credential:string;receiverNonce?:string;senderNonce?:string};
 let view:'start'|'sender'|'receiver'|'security'='start';let roomId='',roomKey='',pin='',credential='',link='',roomState='WAITING',receiverView='PIN',deadline=0,error='',canApprove=false;let pendingReceiverNonce='',senderNonce='';let socket:WebSocket|null=null;let pairingKey:CryptoKey|null=null;let keys:SessionKeys|null=null;let items:Item[]=[];const replay=new ReplayGuard();
 const request=()=>randomId();const wsUrl=()=>`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`;const send=(value:object)=>socket?.send(JSON.stringify({version:1,...value}));
 function save(){if(view!=='sender'&&view!=='receiver')return;const data:Stored={role:view,roomId,roomKey,pin,credential};if(pendingReceiverNonce)data.receiverNonce=pendingReceiverNonce;if(senderNonce)data.senderNonce=senderNonce;sessionStorage.setItem('keybridge.room',JSON.stringify(data))}
 function clear(){sessionStorage.removeItem('keybridge.room');roomKey='';pin='';credential='';keys=null;pairingKey=null;items=[]}
 function connect(first:object){socket=new WebSocket(wsUrl());socket.onopen=()=>send(first);socket.onmessage=event=>void handle(JSON.parse(String(event.data)) as Record<string,unknown>);socket.onclose=event=>{if(event.code!==1000&&event.code!==4001)error='Connection lost. Reload within 60 seconds to reconnect.'}}
 async function createRoom(){clear();view='sender';roomId=base64url(randomBytes(16));roomKey=base64url(randomBytes(32));pin=generatePin();pairingKey=await derivePairingKey(fromBase64url(roomKey),roomId,pin);link=`${location.origin}/#room=${roomId}&key=${roomKey}`;connect({type:'create',roomId,requestId:request()})}
 async function importFragment():Promise<boolean>{const params=new URLSearchParams(location.hash.slice(1));const id=params.get('room'),key=params.get('key');if(!id||!key)return false;history.replaceState(null,'',location.pathname+location.search);if(!/^[A-Za-z0-9_-]{22}$/.test(id)||fromBase64url(key).length!==32){error='Invalid pairing link.';return true}view='receiver';roomId=id;roomKey=key;connect({type:'join',roomId,requestId:request()});return true}
 async function restore(stored:Stored){view=stored.role;roomId=stored.roomId;roomKey=stored.roomKey;pin=stored.pin;credential=stored.credential;pendingReceiverNonce=stored.receiverNonce??'';senderNonce=stored.senderNonce??'';pairingKey=await derivePairingKey(fromBase64url(roomKey),roomId,pin);if(pendingReceiverNonce&&senderNonce)keys=await deriveSessionKeys(pairingKey,roomId,pendingReceiverNonce,senderNonce);if(view==='sender')link=`${location.origin}/#room=${roomId}&key=${roomKey}`;connect({type:'resume',roomId,role:view,credential,requestId:request()})}
 async function submitPin(value:string){try{pin=normalizePin(value);pairingKey=await derivePairingKey(fromBase64url(roomKey),roomId,pin);pendingReceiverNonce=randomId();const envelope=await encryptJson(pairingKey,{roomId,direction:'receiver-to-sender',kind:'pair-request',expiresAt:null},{receiverNonce:pendingReceiverNonce});send({type:'pair',envelope,requestId:request()});receiverView='PENDING';save()}catch{error='The PIN format is invalid.'}}
 async function approve(){if(!pairingKey)return;senderNonce=randomId();keys=await deriveSessionKeys(pairingKey,roomId,pendingReceiverNonce,senderNonce);const envelope=await encryptJson(pairingKey,{roomId,direction:'sender-to-receiver',kind:'pair-response',expiresAt:null},{approved:true,receiverNonce:pendingReceiverNonce,senderNonce});send({type:'approve',envelope,requestId:request()});canApprove=false;save()}
 async function handle(message:Record<string,unknown>){if(message.type==='error'){error=String(message.code);return}if(message.type==='created'){credential=String(message.credential);deadline=Number(message.deadline);roomState=String(message.state);save();return}if(message.type==='joined'){receiverView='PIN';return}if(message.type==='room_state'){roomState=String(message.state);deadline=Number(message.deadline);return}if(message.type==='pair_request'&&view==='sender'&&pairingKey){try{const envelope=message.envelope as EncryptedEnvelope;const body=await decryptJson<{receiverNonce:string}>(pairingKey,envelope);pendingReceiverNonce=body.receiverNonce;canApprove=true;roomState='PAIR_PENDING'}catch{error='Pairing authentication failed. Ask the Receiver to check the PIN.'}return}if(message.type==='approved'&&view==='receiver'&&pairingKey){try{const envelope=message.envelope as EncryptedEnvelope;const body=await decryptJson<{approved:boolean;receiverNonce:string;senderNonce:string}>(pairingKey,envelope);if(body.receiverNonce!==pendingReceiverNonce||!body.approved)throw new Error();senderNonce=body.senderNonce;keys=await deriveSessionKeys(pairingKey,roomId,pendingReceiverNonce,senderNonce);credential=String(message.credential);receiverView='PAIRED';roomState='PAIRED';save()}catch{error='Approval authentication failed.'}return}if(message.type==='rejected'){error='The Sender rejected this pairing request.';receiverView='PIN';return}if(message.type==='ack'&&message.state)roomState=String(message.state);if(message.type==='ack'&&message.deadline)deadline=Number(message.deadline);if(message.type==='resumed'){roomState=String(message.state);deadline=Number(message.deadline);if(view==='receiver'){receiverView='PAIRED';for(const envelope of message.items as EncryptedEnvelope[])await receiveItem(envelope)}return}if(message.type==='item')await receiveItem(message.envelope as EncryptedEnvelope);if(message.type==='revoked')items=items.filter(item=>item.id!==message.itemId);if(message.type==='room_ended'){clear();view='start';error=`Room ended: ${String(message.reason)}`}}
 async function receiveItem(envelope:EncryptedEnvelope){if(!keys||!replay.accept(envelope.messageId)||envelope.expiresAt===null||envelope.expiresAt<=Date.now())return;try{const item=await decryptJson<Item&Record<string,unknown>>(keys.item,envelope);if(item.expiresAt!==envelope.expiresAt)return;items=[...items.filter(old=>old.id!==item.id),item]}catch{error='An encrypted item failed authentication.'}}
 async function sendItem(label:string,value:string,ttl:number){if(!keys)return;const size=new TextEncoder().encode(value).length;if(size>MAX_PLAINTEXT_BYTES){error='Secret text exceeds 64 KiB.';return}const createdAt=Date.now(),expiresAt=createdAt+ttl*1000,id=randomId();const item:Item={id,label,value,createdAt,expiresAt,ttl};const envelope=await encryptJson(keys.item,{roomId,direction:'sender-to-receiver',kind:'item',expiresAt},item);send({type:'item',envelope,requestId:request()});items=[...items,item]}
 function revoke(id:string){send({type:'revoke',itemId:id,requestId:request()});items=items.filter(item=>item.id!==id)}
 function end(){send({type:'end',requestId:request()});clear();view='start'}function leave(){send({type:'leave',requestId:request()});clear();view='start'}
 const expiry=setInterval(()=>items=items.filter(item=>item.expiresAt>Date.now()),1000);onDestroy(()=>{clearInterval(expiry);socket?.close(1000)});
 onMount(async()=>{if(await importFragment())return;const raw=sessionStorage.getItem('keybridge.room');if(raw)try{await restore(JSON.parse(raw) as Stored)}catch{clear();error='The saved room could not be restored.'}});
</script>
<header class="site"><button class="brand" onclick={()=>{if(view==='start'||view==='security')view='start'}}>KeyBridge</button><span>v{__APP_VERSION__}</span></header><main>{#if error}<div class="error" role="alert">{error}<button aria-label="Dismiss error" onclick={()=>error=''}>×</button></div>{/if}{#if view==='start'}<StartRoom onCreate={createRoom} onSecurity={()=>view='security'}/>{:else if view==='sender'}<SenderRoom {link} {pin} state={roomState} {deadline} {items} {canApprove} onApprove={approve} onReject={()=>{send({type:'reject',requestId:request()});pin=generatePin();derivePairingKey(fromBase64url(roomKey),roomId,pin).then(key=>pairingKey=key);canApprove=false}} onSend={sendItem} onRevoke={revoke} onExtend={()=>send({type:'extend',requestId:request()})} onEnd={end}/>{:else if view==='receiver'}<ReceiverRoom state={receiverView} {items} onSubmitPin={submitPin} onRevoke={revoke} onLeave={leave}/>{:else}<section class="panel"><h1>Security &amp; transparency</h1><p>The published browser client encrypts secret payloads before transmission. The Relay does not receive the room key, PIN, or plaintext.</p><p>The Relay sees network addresses, times, room associations, ciphertext sizes, expiry times, and protocol events. The server supplying this page could serve modified JavaScript, so this browser app cannot protect against a malicious code-serving server.</p><p>V1 has no forward secrecy. Clipboard content is not cleared. Browser memory and storage cannot guarantee secure erasure.</p><p>Protocol 1 · Version {__APP_VERSION__} · Source {__SOURCE_COMMIT__}</p><button onclick={()=>view='start'}>Back</button></section>{/if}</main><footer>No accounts · No analytics · Session storage only</footer>
